name: CI/CD with Docker

on:
  push:
    branches:
      - main  # Chạy workflow khi có thay đổi trên nhánh main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code từ repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t kienbeo237/findtutor:$GITHUB_SHA .

      # Đăng nhập vào Docker Hub (hoặc GitHub Container Registry)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Push Docker image lên Docker Hub
      - name: Push Docker image
        run: |
          docker push kienbeo237/findtutor:$GITHUB_SHA

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # SSH vào VPS và kéo Docker image mới
      - name: SSH to VPS and deploy
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            # Kéo Docker image từ Docker Hub
            docker pull kienbeo237/findtutor:$GITHUB_SHA
            # Dừng container cũ nếu có
            docker stop findtutor || true
            # Xóa container cũ
            docker rm findtutor || true
            # Chạy container mới
            docker run -d --name findtutor -p 8080:8080 kienbeo237/findtutor:$GITHUB_SHA
