name: Deploy Spring Boot Backend

on:
  push:
    branches:
      - main  # Chạy khi có thay đổi trên branch main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Spring Boot App
        run: |
          cd home/deploy/backend/ 
          ./mvnw clean package -DskipTests
          mv target/*.jar backend.jar

      - name: Upload Backend to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          source: "backend/backend.jar"
          target: "/home/deploy/backend"

      - name: Restart Backend Service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          script: |
            sudo systemctl restart backend.service
