name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout mã nguồn từ repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Cài đặt Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      # Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Build với Maven
      - name: Build with Maven
        run: mvn clean install -DskipTests=true

      # (Tùy chọn) Chạy Unit Test
      - name: Run Tests
        run: mvn test

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Checkout lại mã nguồn
      - name: Checkout repository
        uses: actions/checkout@v2

      # Tải và cấu hình SSH để triển khai lên VPS
      - name: Set up SSH and deploy to VPS
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan your_vps_ip >> ~/.ssh/known_hosts
          
          # Sao chép JAR file lên VPS
          scp target/FindTutor-0.0.1-SNAPSHOT.jar user@${{ secrets.SSH_PORT }}:/home/deploy/backend

          # SSH vào VPS và chạy ứng dụng
          ssh user@${{ secrets.SSH_PORT }} "nohup java -jar /home/deploy/backend/FindTutor-0.0.1-SNAPSHOT.jar > /home/user/output.log 2>&1 &"
