name: Deploy Spring Boot Backend

on:
  push:
    branches:
      - main  # Chạy khi có thay đổi trên branch main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug Directory Structure
        run: ls -la  # Kiểm tra thư mục sau khi checkout

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Spring Boot App
        run: |
          if [ -d "backend" ]; then cd backend; fi
          ./mvnw clean package -DskipTests
          mv target/*.jar backend.jar
          ls -la  # Kiểm tra xem backend.jar có được tạo không

      - name: Upload Backend to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          source: "backend/backend.jar"
          target: "/home/deploy/backend"

      - name: Restart Backend Service on VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          script: |
            cd /home/deploy/backend
            ls -la  # Kiểm tra xem backend.jar đã được upload chưa
            sudo chmod +x backend.jar
            sudo systemctl restart backend.service
            sudo systemctl status backend.service --no-pager
