name: build and deploy spring-api
on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: build and deploy spring-api
    runs-on: ubuntu-20.04
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: setup jdk 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17
      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo systemctl enable --now docker
      - name: unit tests
        run: mvn -B test --file pom.xml

      - name: build the app
        run: |
          mvn clean
          mvn -B package --file pom.xml

      - name: build the docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          dockerfile: Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_USERNAME }}/rest-api:v1.0.0

      - name: login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: push the docker image to docker hub
        uses: docker/build-push-action@v4
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/rest-api:v1.0.0
      - name: SSH into VPS and deploy the docker container
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            # Pull the latest Docker image from Docker Hub
            docker pull ${{ secrets.DOCKER_USERNAME }}/rest-api:latest
            # Stop and remove the existing container if it's running
            docker stop rest-api || true
            docker rm rest-api || true
            # Run the container with port mapping and detach mode
            docker run -d --name rest-api -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/rest-api:latest